### ISSUE TITLE
Add support for directly using a docker image as an action

### ISSUE THREAD

**Issue by rajbos** [devops-actions/load-used-actions#6]
You can use a docker image straight from the uses command:

``` yaml
- uses: docker://path-to-container-registry/name:label
  env:
    my-var: value
``` 

We currently extract these as an action with name: `docker://path-to-container-registry/name:label` and without a version.

- [ ] Detect them as a docker image
- [ ] Remove them from the actions listings
- [ ] Export them as a separate list to the output
